name: Unzip Files
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Unzip file
        run: |
          tar -xzvf code.tar.gz
          rm code.tar.gz
          
      - name: Debug - List files
        run: |
          ls -al  # 列出当前目录所有文件
          pwd    # 打印当前路径
          
      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
