name: Unzip Files
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，确保分支同步
          ref: main  # 明确指定拉取 main 分支

      - name: Unzip file
        run: |
          tar -xzvf code.tar.gz
          rm code.tar.gz  # 解压后删除压缩包

      - name: Force commit and push
        run: |
          # 配置 Git 身份
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 强制添加所有文件（包括被忽略的文件，可选）
          git add -f .
          
          # 无论是否有变更，强制提交（避免无变更时失败）
          git commit -m "Unzip and push code" || echo "No changes, but force push anyway"
          
          # 强制推送到远程 main 分支，覆盖远程内容
          git push origin main --force
